### ISSUE TITLE
MODS: index BCE dates for coin collection

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sw-indexer-service#43]
from SW-1453

"More fun with dateCreated... This record has B.C. dates. We REALLY need a better display for B.C. dates that "-17--15" which should translate to "18 B.C.-16 B.C." In this collection B.C. dates are encoded "edtf". 1 B.C. = "0000", then 2 B.C.="-0001", so for years earlier than 1 B.C. the display should suppress hyphen, suppress leading zeroes, increase the numeral by one, and (crucially!) add "B.C." It's complicated, but the current display is horrible and the donor is not happy about it. "

druids for coins with BCE dates:

bb408km1389
fp708mh2112
jb279cg9840
cs470ng8064
nr278nn0626
hs628wg6771

https://purl.stanford.edu/hs628wg6771.mods

Where does this show up in SW?
- [x] search results  
  - [x] Solr field:  create a string display field for dates?  use formerly defunct pub_date_display?
  - [x] stanford-mods has method to get right values
  - [x] sw-indexer-service populates Solr field 
- [x] record view  @jvine says "the record for for mods records is fine" - presumably mods-display gem is clever enough.
- [x] date slider
  - [x]  Solr field: pub_year_tisim
  - [x] stanford-mods pub_year_int   method has correct data
  - [x]  #38  puts this data into the right Solr field
  - [x] does date slider work for negative dates?  confirmed that it doesn't blow up
- [x] date sorting
- [x] MODS display  @jvine   is this already ok?

Then index and review?

**Comment by ndushay** [comment]
related to 

sul-dlss/stanford-mods#56  display dates before 1000
sul-dlss/stanford-mods#53  u and uu dates

**Comment by jvine** [comment]
MODS display is already OK.

**Comment by ndushay** [comment]
per 1:1 discussions with @jvine and @jkeck , it seems we are happy with what comes from mods-display gem, so i will try to get indexing code to utilize mods-display date parsing to populate index field, rather than recreate stuff.

**Comment by ndushay** [comment]
From conversation with @jvine re:  Search Results:

```
"for marc records, we have something like:   Title [date] 
where we pick a date or date range that best identifies the work (and explains the sort order, perhaps)
and we have the imprint, with no label - just placed there like so:  4th edition. - Boston : Pearson, [2017]
so the whole imprint would be fine for MODS records as well
but we also kind of want a separate date to go with the title.

if we can’t get to that date easily, the imprint alone will answer the requirement for the roman coins collection
```

the Date  part of Title[Date]  is the SW index notion of pub date.   pub dates from MODS choose dateIssued elements first;  if none, dateCreated, if none, dateCaptured.


from mods_display gem and conversation with @jkeck,  there is clearly a "Date created" piece of data in the imprint info that has the  BC/AD date stuff;  however there is NOT separate "Date issued" piece of data - it is part of "Imprint", and it does NOT get the nice B.C  formatting.

Since "pub date" is algorithm chooses dateIssued first,  using mods_display as it is right now will miss dateIssued information.

**Comment by ndushay** [comment]
@jkeck said further:  " So the BC/AD dates stuff was just added (as kind of a quick-fix).  Perhaps ModsDisplay is not handling encoded dates in that particular field [dateIssued]  right now."

**Comment by ndushay** [comment]
More from @jvine:

me:  "do you want me to get a representation of the single pub date for sorting to go in  Title[Date]?  or do you want me to get something more complete (e.g. a range such as "19 B.C.-18 B.C.")"

```range is good, if there is one.  we show ranges for MARC records```

note that this means we use various flavored xxx_year_isi   fields for Title[Date]  in SW

**Comment by ndushay** [comment]
determining if date slider works with negative dates is blocked by #https://github.com/sul-dlss/sw-indexer-service/issues/46  (and then indexing roman coins, once indexing works.)

**Comment by ndushay** [comment]
date slider ok;   Solr field for date slider is getting negative values (good) and date slider isn't blowing up (good).
date sort:  Solr field is getting negative values (good) and sort appears to be correct (good)

**Comment by ndushay** [comment]
Coding complete with #52;  indexing is all that remains.
