### ISSUE TITLE
MODS Indexing: Virtual object

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/sw-indexer-service#47]
Add set and set with title in parallel with collection and collection with title by way of the isConstituentOf field in the MODS

part of indexing for sul-dlss/SearchWorks#1051

example child
http://searchworks-test.stanford.edu/preview/view/yr145dc7638
and parent
http://searchworks-test.stanford.edu/preview/view/10449093

**Comment by ndushay** [comment]
This is currently blocked by sul-dlss/dor-services#128 as we can't index data unless it is in public xml

**Comment by ndushay** [comment]
The missing information will be in purl-test today if all goes well, per @blalbrit.   If it passes muster in purl-test, it will need to be deployed to purl prod, the robots will need to be redeployed, and the (single?) record will need to be republished.

**Comment by blalbrit** [comment]
Parent Object: https://purl-test.stanford.edu/hj097bm8879.xml
Example Child Object: https://purl-test.stanford.edu/bv599bt4452.xml

**Comment by blalbrit** [comment]
(note - all 24 objects need to be republished when code is deployed to prod - but that is negligible effort... minutes not hours).

**Comment by ndushay** [comment]
indexing code is in sw-indexer-service.  When sw-indexer-service is redeployed, and when the data is ready and item-release is ready, then we should be able to index virtual objects.
